name: example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get: ^4.6.6
  sm_widget:
    path: ../
  url_launcher: ^6.2.5
  html: ^0.15.4
  extended_list: ^3.0.1

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_gen:
  output: lib/generated
