name: sm_widget
description: "A Flutter package with widgets, containing implementations of
  commonly used Flutter widgets."
version: 0.0.6
homepage: "https://github.com/shay-wong/flutter_sm_widget"
repository: "https://github.com/shay-wong/flutter_sm_widget"
issue_tracker: "https://github.com/shay-wong/flutter_sm_widget/issues"

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  sm_image: ^0.0.3
  sm_network: ^0.0.6
  extended_text: ^13.0.0
  extended_text_field: ^14.0.0
  extended_text_library: ^12.0.0
  sm_logger: ^0.0.7

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
