name: flutter_sm_widget
description: "A new Flutter package project."
version: 0.0.1+4
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sm_image:
    git:
      url: https://github.com/shay-wong/flutter_sm_image.git
      ref: main
  flutter_sm_network:
    git:
      url: https://github.com/shay-wong/flutter_sm_network.git
      ref: main
  get: ^4.6.6
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
